config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  devise_for :users

  resources :users do
    member do
      get :likes
    end
  end

  resources :books do
    resources :reviews, except: :index
  end
  
  # root "books#favorite"
  resources :reviews, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :category
  # has_many :reviews, dependent: :destroy
  belongs_to :review, dependent: :destroy
  # has_many :users, through: :reviews
  belongs_to :user
  has_one_attached :image
  attribute :new_image

  validates :title, presence: true, length: { maximum: 50 }
  
  validates :new_image, presence: true
  before_save do
    self.image = new_image if new_image
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
  # enum evaluations: { one: 1, two: 2, three: 3, four: 4, five: 5 }
  # def which_number?
  #   enum evaluations: { one: 1, opf: 1.5, two: 2, wpf: 2.5, three: 3, tpf: 3.5, four: 4, fpf: 4.5, five: 5 }
  # end

  validates :title, presence: true, length: { maximum: 50 }
  validates :reading_date, presence: true
  validates :evaluation, presence: true
  # validates :evaluation, numericality: true
  validates :description, presence: true, length: { maximum: 140 }
  validates_uniqueness_of :book_id, scope: :user_id

  has_many :favorites, foreign_key: 'review_id', dependent: :destroy
  has_many :users, through: :favorites

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  has_one_attached :avatar

  has_many :reviews

  has_many :favorites
  has_many :favrevs, through: :favorites, source: :review

  # def like(review)
  #   favorites.find_or_create_by(review_id: review.id)
  # end

  # def unlike(review)
  #   favorite = favorites.find_by(review_id: review.id)
  #   favorite.destroy if favorite
  # end

  # def favrev?(review)
  #   self.favrevs.include?(review)
  # end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected 
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nick_name, :avatar])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update, :destroy]
  
  def index
    @books = Book.with_attached_image.page(params[:page]).per(4)
  end

  def show
    @book = Book.with_attached_image.includes(review: :user).find(params[:id])
  end
  
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book, notice: "bookを収納しました。"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: "本を再収納しました。"
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path, notice: "本棚から外しました。"
  end

  # def favorite
  #   @book.favorite
  #   redirect_to book_path, notice: "お気に入りに登録しました。"
  # end

  private

  def book_params
    params.require(:book).permit(:title, :category_id, :new_image)
  end

  def set_book
    @book = Book.find(params[:id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    review = Review.find(params[:review_id])
    current_user.like(review)
    flash[:success] = "お気に入りに登録しました。"
    redirect_back(fallback_location: root_path)
  end

  def destroy
    review = Review.find(params[:review_id])
    current_user.unlike(review)
    flash[:success] = "お気に入り登録を解除しました。"
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_book, only: [:show, :new, :create, :edit]
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def new
    @review = Review.new
  end 
  
  def create
    @review = Review.new(review_params)
    @review.attributes = {
      book_id: params[:book_id],
      user_id: current_user.id
    }
    if @review.save
      redirect_to @review.book, notice: "レビューを書き込みました。"
    else
      render :new
    end
  end
  
  def show
  end

  def edit
  end

  def update
    if @review.update(review_params)
      redirect_to @review.book, notice: "レビューを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to @review.book, notice: "レビューを削除しました。"
  end
  
  private 
  
  def review_params
    params.require(:review).permit(:title, :reading_date, :evaluation, :description)
  end 
  
  def set_book
    @book = Book.find(params[:book_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def likes
    @user = User.find(params[:id])
    @favrevs = @user.favrevs.page(params[:page])
    counts(@user)
  end

  def like(review)
    favorites.find_or_create_by(review_id: review.id)
  end

  def unlike(review)
    favorite = favorites.find_by(review_id: review.id)
    favorite.destroy if favorite
  end

  def favrev?(review)
    self.favrevs.include?(review)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def show_book_image(book)
    if book.image.attached?
      image_tag book.image.variant(resize: "300x300"), class: "img-thumbnail"
    else
      image_tag "no_image.png", class: "img-thumbnail"
    end
  end
  def show_book_small_image(book)
    if book&.image&.attached?
      image_tag book.image.variant(resize: "50x50"), class: "img-thumbnail"
    else
      image_tag "no_image.png", class: "img-thumbnail", width: 50
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: book, local: true do |form| %>
  <%= render "shared/errors", obj: book %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name , { include_blank: t(".include_blank") },  { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= form.label :new_image %>
    <%= form.file_field :new_image, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
  <%= link_to '戻る', :back, class: "btn btn-secondary" %>
<% end %>

app/views/books/edit.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <%= render 'form', book: @book %>
</div>

app/views/books/index.html.erb
<% @books.each do |book| %>
  <div class="col-lg-3 col-md-4 col-sm-6 mb-3">
    <div class="mx-auto"><%= link_to show_book_image(book), book_path(book) %></div>
    <h4 class="mt-2"><%= link_to book.title, book_path(book) %></h4>
  </div>
<% end %>

<div class="col-12">
  <%= paginate @books %>
</div>

app/views/books/new.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <%= render 'form', book: @book %>
</div>

app/views/books/show.html.erb
<div class="col-md-10 offset-md-1 mt-5">
  <div class="row">
    <div class="col-md-4 mb-4">
      <%= show_book_image @book %>
    </div>
    <div class="col-md-8">
      <h2><%= @book.title %></h2>
      
      <%= render partial: "reviews/review", collection: @book.review %>
    </div>
  </div>
  <%= link_to t(".edit"), edit_book_path(@book), class: "btn btn-primary" %>
  <%= button_tag t(".delete"), class: "btn btn-warning", data: { toggle: "modal", target: "#delete-book" } %>
  <% if user_signed_in? %>
    <%= link_to t(".review_new"), new_book_review_path(@book), class: "btn btn-info" %>
  <% end %>

  <% @reviews.each do |review| %>
    <% if current_user.favrev?(review) %>
      <%= form_for(current_user.favorites.find_by(review_id: review.id), html: { method: :delete }) do |f| %>
        <%= hidden_field_tag :review_id, review.id %>
        <%= f.submit t(".favorite_out"), class: 'btn btn-danger' %>
      <% end %>
    <% else %>
      <%= form_for(current_user.favorites.build) do |f| %>
        <%= hidden_field_tag :review_id, review.id %>
        <%= f.submit t(".favorite"), class: 'btn btn-success' %>
      <% end %>
    <% end %>
    <%= link_to t(".return"), books_path(@book), class: "btn btn-secondary" %>
    <hr>
  <% end %>
</div>
<%# deleteのmodal %>
<div class="modal fade" id="delete-book">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t(".modal_title") %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= t(".question_book", book: @book.title) %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(".cancel") %></button>
        <%= link_to t(".delete_action"), book_path(@book), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>
<%# favoriteのmodal %>
<div class="modal fade" id="favorite-book">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t(".favorite_title") %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= t(".favorite_book", book: @book.title) %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(".cancel") %></button>
        <%= link_to t(".favorite_action"), book_path(@book), class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

  <%# カテゴリー %>
  <%# <ul> %>
    <%# <li><b>価格: </b><%= number_with_delimiter @book.price %>
    <%# <li><b>読了日: </b><%= @book.finished_date %>
  <%# </ul> %>
  <%# <h4>3つの学び</h4> %>
  <%# <ul> %>
    <%# <li><b>読了日: </b><%= @book.finished_date %>
    <%# <li><b>読了日: </b><%= @book.finished_date %>
    <%# <li><b>読了日: </b><%= @book.finished_date %>
  <%# </ul> %>
  <%# <hr> %>
  <%# <h4>140字まとめ</h4> %>
  <%# <%= simple_format @book.description %>

app/views/favorites/_like_button.html.erb
<% if current_user.favrev?(review) %>
  <%= form_for(current_user.favorites.find_by(review_id: review.id), html: { method: :delete }) do |f| %>
    <%= hidden_field_tag :review_id, review.id %>
    <%= f.submit 'お気に入り登録解除', class: 'btn btn-danger' %>
  <% end %>
<% else %>
  <%= form_for(current_user.favorites.build) do |f| %>
    <%= hidden_field_tag :review_id, review.id %>
    <%= f.submit 'お気に入り登録', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookTwitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render "shared/flash" %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with model: [book, review], local: true do |form| %>
  <%= render "shared/errors", obj: review %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :reading_date %>
    <%= form.text_field :reading_date, class: "form-control" %>
  </div>

  <div class="form-group" id="star">
    <%= form.label :evaluation %><br>
    <%= form.hidden_field :evaluation, class: "form-control", id: :review_star %>
  </div>

  <!-- 評価 hidden_field-->
  <!-- 評価javascript -->
  <script>
  $('#star').raty({
    size     : 60,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',
    starHalf: '<%= asset_path('star-half.png') %>',
    scoreName: 'review[evaluation]',
    half: true,
  });
  </script>  

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 8, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
  <%= link_to t(".back"), :back, class: "btn btn-secondary" %>
<% end %>

app/views/reviews/_review.html.erb
<div>
  <div> 
    <div>
      <ul>
        <li><b><%= t ".category" %>: </b><%= @book.category&.name %></li>
        <li><b><%= t ".evaluation" %>: </b><span class="text-warning"><%= "★" * review.evaluation %></span></li>
        <li><b><%= t ".created_at" %>: </b><%= review.created_at.strftime("%Y.%m.%d") %></li>
        <li><b><%= t ".title" %>: </b><%= link_to review.title, book_review_path(review.book, review) %></li>
      </ul>
    </div>
  </div>
  <%= simple_format review.description %>
  <div>
    <%= render 'favorites/like_button', review: review %>
  </div>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-8 offset-md-2 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <div class="mb-3">
    <%= show_book_small_image @book %>
    <span><%= @book.title %></span>
  </div>
  <hr>
  <%= render partial: 'form', locals: { book: @book, review: @review } %>
</div>

app/views/reviews/new.html.erb
<div class="col-md-8 offset-md-2 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <div class="mb-3">
    <%= show_book_small_image @book %>
    <span><%= @book.title %></span>
  </div>
  <hr>
  <%= render partial: 'form', locals: { book: @book, review: @review } %>
</div>

app/views/reviews/show.html.erb
<div class="col-md-8 offset-md-2 mt-5">
  <h2 class="text-center"><%= t ".title" %></h2>
  <div>
    <% if @review.user.avatar.attached? %>
      <%= image_tag @review.user.avatar.variant(resize: "60x60"), class: "img-thumbnail" %>
    <% else %>
      <%= image_tag "no_image.png", class: "img-thumbnail", width: 60 %>
    <% end %>
    <span><%= @review.user.nick_name %></span>
  </div>
  <hr>
  <div>
    <div>
      <span class="text-warning"><%= "★" * @review.evaluation %></span>
      <b><%= @review.title %></b>
    </div>
    <small><%= @review.created_at.strftime("%Y年%m月%d日") %></small>
  </div>
  <%= simple_format @review.description %>
  <% if user_signed_in? && current_user.id == @review.user_id %>
    <%= link_to t(".edit"), edit_book_review_path(@book, @review), class: "btn btn-info" %>
    <%= button_tag t(".delete"), class: "btn btn-warning", data: { toggle: "modal", target: "#delete-review" } %>
  <% end %>
  <%= link_to t(".back"), @book, class: "btn btn-secondary" %>
</div>

<div class="modal fade" id="delete-review">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t(".modal_title") %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= t(".question_review", review: @review.title) %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(".chancel") %></button>
        <%= link_to t(".delete_action"), book_review_path(@book, @review), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
  <div class="alert alert-success" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-danger" role="alert">
    <%= flash.alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to t(".title"), root_path, class: "navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to t(".home"), root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".new_book"), new_book_path, class: "nav-link" %>
      </li>
      <%# お気に入りのパスを変更 OK? %>
      <li class="nav-item">
          <%= link_to t(".お気に入り"), users_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to t(".edit_registration"), edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t(".log_out"), destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t(".new_registration"), new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t(".log_in"), new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-info my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/users/index.html.erb
<%# <% @favrevs.each do |favrev| %>
  <%# <div class="col-lg-3 col-md-4 col-sm-6 mb-3"> %>
    <%# <div class="mx-auto"><%= link_to show_book_image(favrev), book_path(favrev) %></div> %>
    <%# <h4 class="mt-2"><%= link_to favrev.title, book_path(favrev) %></h4> %>
  <%# </div> %>
<%# <% end %> %>

<%# <div class="col-12"> %>
  <%# <%= paginate @favrevs %> %>
<%# </div> %>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="media-object img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>"><%= link_to user_path(@user) do %>Reviews <span class="badge"><%= @count_reviews %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
      <li class="<%= 'active' if current_page?(likes_user_path(@user)) %>"><%= link_to likes_user_path(@user) do %>Likes<span class="badge"><%= @count_favrevs %></span><% end %></li>
    </ul>
    <%= render 'reviews/reviews', reviews: @favrevs %>
  </div>
</div>